//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorksAssign.Persistence
{
    using System;
    using System.Collections.Generic;

    public partial class Vx_AllDevice
    {
        public string Id { get; set; }
        public string SubstationName { get; set; }
        public string SubstationVoltage { get; set; }
        public string ScreenName { get; set; }
        public string DeviceName { get; set; }
        public string Voltage { get; set; }
        public string Type { get; set; }
        string _model;
        public string Model {
            get { return _model != null ? _model.Replace(";", Environment.NewLine) : null; }
            set { _model = value; }
        }
        public string Vendor { get; set; }

        string _version;
        public string Version {
            get { return _version != null ? _version.Replace(";", Environment.NewLine) : null; }
            set { _version = value; }
        }

        //   public string Version { get; set; }

        string _buildDate;
        public string BuildDate {
            get { return _buildDate != null ? _buildDate.Replace(";", Environment.NewLine) : null; }
            set { _buildDate = value; }
        }

        string _crc;
        public string CRC {
            get { return _crc != null ? _crc.Replace(";", Environment.NewLine) : null; }
            set { _crc = value; }
        }
        public Nullable<System.DateTime> ProducedDate { get; set; }
        public Nullable<bool> Enable { get; set; }
        public string Comment { get; set; }
        public string PhotoPath { get; set; }
        public string FilePath { get; set; }
    }
}
