//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorksAssign.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vx_AllDevice
    {
        public string Id { get; set; }
        public string SubstationName { get; set; }
        public string SubstationVoltage { get; set; }
        public string ScreenName { get; set; }
        public string DeviceName { get; set; }
        public string Voltage { get; set; }
        public string Type { get; set; }
        public string Model { get; set; }
        public string Vendor { get; set; }
        public string Version { get; set; }
        public string BuildDate { get; set; }
        public string CRC { get; set; }
        public Nullable<System.DateTime> ProducedDate { get; set; }
        public Nullable<bool> Enable { get; set; }
        public string Comment { get; set; }
        public string PhotoPath { get; set; }
        public string FilePath { get; set; }
    }
}
