//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorksAssign.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_AllPoints
    {
        public System.DateTime WorkDate { get; set; }
        public string WorkType { get; set; }
        public string WorkContent { get; set; }
        public long EmpId { get; set; }
        public string Name { get; set; }
        public string RoleName { get; set; }
        public double RoleWgt { get; set; }
        public double TypeWgt { get; set; }
    }
}
